[timeline-chart][tsp-typescript-client] Switch to solid versions
eclipse-cdt-cloud/theia-trace-extension pull request #1068
Opened 2024-04-08 15:20 UTC by marcdumais-work

Now that we can easily publish solid (latest) revisions of these dependencies, let's switch to requesting a "solid" version range, for them, instead of using "next". From now-on, these dependencies should be managed like any other production dependencies.

2024-04-09 20:21 UTC, bhufmann requested changes

2024-04-10 13:15 UTC, marcdumais-work commented on yarn.lock
>    version "1.0.0"
Good catch! Fixed.

2024-04-10 15:01 UTC, bhufmann approved these changes
Thank you!

2024-04-10 15:51 UTC, marcdumais-work commented
Thanks for the review! Merging.

2024-04-10 15:51 UTC, merged