Upgrade ag grid
eclipse-cdt-cloud/theia-trace-extension pull request #1094
Opened 2024-07-22 19:17 UTC by marcdumais-work

2024-08-23 18:48 UTC, bhufmann requested changes
It looks good to me. I tested with Events Table and Latency Table. I have comment though which I'd like you to fix. Thanks

2024-08-23 19:06 UTC, marcdumais-work commented
> Please open a tracker for the disabled unit tests to not forget.

https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/1100

2024-08-23 19:07 UTC, marcdumais-work commented on packages/react-components/src/components/table-output-component.tsx
I will look into that

2024-08-26 14:30 UTC, marcdumais-work commented on packages/react-components/src/components/table-output-component.tsx
ok, I think I have figured it out. It seems some defaults have changed since the previous `ag-grid` version we were using, and so we needed to tweak the column config to retain the previous behavior. I will soon push a version that has an extra commit, that does that.

Good catch on your part, BTW.

2024-08-26 14:37 UTC, marcdumais-work commented on packages/react-components/src/components/table-output-component.tsx
done

2024-08-26 17:39 UTC, bhufmann commented on packages/react-components/src/components/table-output-component.tsx
Thanks

2024-08-26 17:40 UTC, bhufmann reviewed
I tested the new version and it looks good. Could you please re-arrange the commits to logical increments that work independently? Then I'll approve it. Thanks

2024-08-26 18:02 UTC, marcdumais-work commented
> I tested the new version and it looks good. Could you please re-arrange the commits to logical increments that work independently? Then I'll approve it. Thanks

done - down to 3 commits that I think are logical increments

2024-08-26 20:50 UTC, marcdumais-work commented
> > I tested the new version and it looks good. Could you please re-arrange the commits to logical increments that work independently? Then I'll approve it. Thanks
> 
> done - down to 3 commits that I think are logical increments

New version pushed that contains 2 commits

2024-08-27 13:01 UTC, bhufmann approved these changes
Looks good to me. Thanks for the upgrade of ag-grid.

2024-08-27 13:38 UTC, marcdumais-work commented
Thanks for the review!

2024-08-27 13:38 UTC, merged