Hide empty rows when filter is applied
eclipse-cdt-cloud/theia-trace-extension pull request #1120
Opened 2024-09-23 15:35 UTC by PatrickTasse

Hide rows that have no non-null state in their model, when a filter is applied. Gaps between states in the row model should be make rows visible when strategy is SAMPLED, but not when it is DEEP.

Keep an up-to-date list of empty nodes after fetching row models from the server.

Add emptyNodes and hideEmptyNodes to the properties of EntryTree, Tree and Table. Filter the empty nodes when rendering the Table.

Remove the updateSearchFilters callback when adding or removing a filter as the state change will handle it already.

Removed unused dataRows in TimegraphOuputState

2024-09-23 15:36 UTC, PatrickTasse commented
Requires https://github.com/eclipse-cdt-cloud/timeline-chart/pull/296

2024-09-24 14:27 UTC, bhufmann requested changes
It works well. I found one issue though. The filter expression (hide or search) filter is not applied anymore after removing or adding annotations (e.g. lost events).

2024-09-24 17:07 UTC, PatrickTasse commented
> It works well. I found one issue though. The filter expression (hide or search) filter is not applied anymore after removing or adding annotations (e.g. lost events).

Fixed with https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1123

2024-09-25 14:50 UTC, bhufmann approved these changes
Looks good to me. I tested it with small and large traces. Thanks! 

I rebased it to current master with before testing. Please do so as well.

2024-09-26 15:09 UTC, merged