Use filter table tree for Available Views view implementation
eclipse-cdt-cloud/theia-trace-extension pull request #1128
Opened 2024-10-10 19:59 UTC by bhufmann

- Use FilterTree
- Add tooltips to TreeNode and TableCell
- Enable sorting and filter
- Description of view is part of the tooltip instead of being printed below view name

fixes #1113

![vscode-new-available-view2](https://github.com/user-attachments/assets/8dbf8d0d-394e-44c3-bb93-ff6698f0be7b)

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

2024-10-11 19:16 UTC, bhufmann commented on packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
> +                    <FilterTree
should we move this into AvailableViewComponent? Then the Overview menu item to select the xy output would have it as well.

2024-10-24 14:36 UTC, PatrickTasse requested changes
Now matter how wide the Available Views panel is resized, its scrollable content is just a little bit wider than the available width, so a horizontal scrollbar appears unnecessarily with a very small scrollable range. There might be some margin width unnaccounted for somewhere.

2024-10-24 19:27 UTC, bhufmann commented
> Now matter how wide the Available Views panel is resized, its scrollable content is just a little bit wider than the available width, so a horizontal scrollbar appears unnecessarily with a very small scrollable range. There might be some margin width unnaccounted for somewhere.

This should be fixed in the updated version

2024-10-31 18:43 UTC, PatrickTasse approved these changes

2024-11-01 12:57 UTC, merged