refactor(SignalManager): improve type safety and reduce boilerplate
eclipse-cdt-cloud/theia-trace-extension pull request #1133
Opened 2024-10-22 19:14 UTC by williamsyang-work

- Replace individual fire* methods with strongly-typed emit interface
- Consolidate signal payload types into single Signals interface
- Add type-safe event handler registration with overloaded on/off methods
- Remove redundant method declarations in favor of TypeScript inference
- Maintain full backward compatibility with existing event system

The new implementation provides compile-time type checking for event payloads while significantly reducing code volume and maintenance burden.

2024-10-24 19:12 UTC, bhufmann requested changes
Thanks for the proposal. It looks like a simplification. I had a first glance over the changes and have a general comment using Strings. Please have look.

2024-10-28 20:00 UTC, bhufmann commented
FYI @ngondalia

2024-10-28 20:11 UTC, bhufmann commented
@williamsyang-work I want to understand the impact to the vscode-trace-extension. I'm currently struggling to make it compile for the external-api (https://github.com/eclipse-cdt-cloud/vscode-trace-extension/blob/e1bfcee1493621b060889a0e79c993c0748931d5/vscode-trace-extension/src/external-api/external-api.ts#L78). 

Any suggestion?

2024-10-29 13:09 UTC, bhufmann commented
> @williamsyang-work I want to understand the impact to the vscode-trace-extension. I'm currently struggling to make it compile for the external-api (https://github.com/eclipse-cdt-cloud/vscode-trace-extension/blob/e1bfcee1493621b060889a0e79c993c0748931d5/vscode-trace-extension/src/external-api/external-api.ts#L78).
> 
> I get the following error
> 
> ```
> Argument of type 'string | symbol' is not assignable to parameter of type 'keyof Signals'.
>   Type 'string' is not assignable to type 'keyof Signals'.ts(2345)
> ```
> 
> Any suggestions?

I think we could change the API

```Javascript
 offSignalManagerSignal(event: string | symbol, listener: (...args: unknown[]) => void): void {
        signalManager().off(event, listener);
    },
```

to the following 

```Javascript
offSignalManagerSignal(event: keyof Signals, listener: (...args: unknown[]) => void): void {
        signalManager().off(event, listener);
    },
```

This will break downstream projects. @ngondalia please let us know if that is ok with you.

2024-10-29 18:58 UTC, ngondalia commented
> > @williamsyang-work I want to understand the impact to the vscode-trace-extension. I'm currently struggling to make it compile for the external-api (https://github.com/eclipse-cdt-cloud/vscode-trace-extension/blob/e1bfcee1493621b060889a0e79c993c0748931d5/vscode-trace-extension/src/external-api/external-api.ts#L78).
> > I get the following error
> > ```
> > Argument of type 'string | symbol' is not assignable to parameter of type 'keyof Signals'.
> >   Type 'string' is not assignable to type 'keyof Signals'.ts(2345)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any suggestions?
> 
> I think we could change the API
> 
> ```js
>  offSignalManagerSignal(event: string | symbol, listener: (...args: unknown[]) => void): void {
>         signalManager().off(event, listener);
>     },
> ```
> 
> to the following
> 
> ```js
> offSignalManagerSignal(event: keyof Signals, listener: (...args: unknown[]) => void): void {
>         signalManager().off(event, listener);
>     },
> ```
> 
> This will break downstream projects. @ngondalia please let us know if that is ok with you.

This will require a bit of refactoring on our end, but i think it is a good improvement. I am ok with this. :)

2024-10-29 20:57 UTC, williamsyang-work commented
Here is a draft PR I made with changes to the `vscode-trace-extension`.  @ngondalia I changed the `ExternalAPI` typing so that the type enforcement will work in downstream projects.

2024-10-31 18:03 UTC, bhufmann submitted a review, later dismissed
Code looks good to me. I ran it in Theia and with the vscode extension update (https://github.com/eclipse-cdt-cloud/vscode-trace-extension/pull/277) and it works. 

BTW, the license error is taken care of and we can still proceed with merging this PR:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/16973

2024-10-31 18:19 UTC, bhufmann commented
@ngondalia would you be able to do another review for this one? If not, please let me know and then I'll ask another committer.

2024-11-01 15:05 UTC, ngondalia commented
> @ngondalia would you be able to do another review for this one? If not, please let me know and then I'll ask another committer.

Yeah, i can review it - Give me until the end of the day (I would like to try it out with both updates)

2024-11-01 15:58 UTC, ngondalia commented
;

> > @ngondalia would you be able to do another review for this one? If not, please let me know and then I'll ask another committer.
> 
> Yeah, i can review it - Give me until the end of the day (I would like to try it out with both updates)

There are some merge conflicts - otherwise LGTM

2024-11-04 13:33 UTC, bhufmann requested changes
@williamsyang-work there are linter errors. Please run `yarn format:write` to fix them and then re-submit the changes.

2024-11-13 17:54 UTC, PatrickTasse submitted a review, later dismissed
I too was worried about not having an enum or constants for the signal names, but the auto-complete does give the list of possible signals.

2024-11-20 22:56 UTC, williamsyang-work commented on packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
> +        signalManager().on("EXPERIMENT_CLOSED", this._onExperimentClosed);
Done.  Sorry for the delay.  @bhufmann

2024-11-26 15:46 UTC, bhufmann commented on packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
> +        signalManager().on("EXPERIMENT_CLOSED", this._onExperimentClosed);
No problem. I'll re-review.

2024-11-26 15:48 UTC, bhufmann approved these changes
It looks good to me. Thanks for the contribution.

2024-11-28 16:25 UTC, MatthewKhouzam approved these changes
I like this approach. I am approving but make sure to merge only when ready.

2024-12-02 21:46 UTC, merged