GraphQL ADR: update content of Testability section
eclipse-cdt-cloud/theia-trace-extension pull request #717
Opened 2022-03-24 21:42 UTC by marco-miller

Base that content on a personal digest (an ADR-focused summary) of [1].

[1] https://app.pluralsight.com/library/courses/apollo-testing

Signed-off-by: Marco Miller <marco.miller@ericsson.com>

2022-03-28 19:59 UTC, Rodrigoplp-work requested changes

2022-03-29 12:57 UTC, marco-miller commented on doc/adr/0002-GraphQL.md
> +* but GraphQL already supports multiple popular languages with testability features.
Done. I made these items part of their own small list (of related items).

2022-03-29 12:59 UTC, marco-miller commented
The other (unrelated) diffs from this last force-push come from the rebase I pushed alongside.

2022-03-29 13:31 UTC, Rodrigoplp-work approved these changes

2022-03-29 18:46 UTC, bhufmann approved these changes
LGTM. Thanks!

2022-03-29 19:33 UTC, merged