Add contribution documentation
eclipse-cdt-cloud/theia-trace-extension pull request #728
Opened 2022-04-04 19:55 UTC by hoangphamEclipse

This commit adds CONTRIBUTION.md and modifies README.md to inform contributors of important contribution policies, legal documents, agreements and guidelines.

2022-04-05 18:14 UTC, bhufmann requested changes
Thanks for the guide. I have some comments for to update.

2022-04-05 18:14 UTC, bhufmann commented on CONTRIBUTION.md
> +
Line 19-22 can be removed, but move the 3 chapters for code-of-conduct, dev process and ECA move here.

2022-04-05 18:14 UTC, bhufmann commented on CONTRIBUTION.md
> +### Pull request guidelines
Since the other chapters are move up, have this chapter as heading 2: ## Pull request guidelines

2022-04-05 18:14 UTC, bhufmann commented on CONTRIBUTION.md
> +### New contributors
Since the other chapters are moved up, have this chapter as heading 2: ## New contributors

2022-04-05 18:14 UTC, bhufmann commented on CONTRIBUTION.md
> +#### Explore the project context
Since the other chapters are move up, have this chapter as heading 3: ### Explore the project context

2022-04-05 18:14 UTC, bhufmann commented on CONTRIBUTION.md
> +#### Start with a small change
Since the other chapters are move up, have this chapter as heading 3: ### Start with a small change

2022-04-05 18:14 UTC, bhufmann commented on CONTRIBUTION.md
> +## Code of Conduct
As I mentioned above move this one up.

2022-04-05 18:14 UTC, bhufmann commented on CONTRIBUTION.md
> +## Eclipse Development Process
As I mentioned above move this one up.

2022-04-05 18:14 UTC, bhufmann commented on CONTRIBUTION.md
> +## Eclipse Contributor Agreement
As I mentioned above move this one up.

2022-04-05 19:46 UTC, bhufmann requested changes
The new file is supposed to be called `CONTRIBUTING.md` and not `CONTRIBUTION.md`. Please rename

2022-04-05 19:46 UTC, bhufmann commented on README.md
Sentence in line 7 needs to be updated and point to the CONTRIBUTING.md file:
Read our [contributor guide](CONTIBUTING.md) and follow the instructions to contribute code.

2022-04-05 19:46 UTC, bhufmann commented on README.md
>  This trace viewer depends on code from several other repos. Sometimes resolving issues in the trace viewer repo requires making changes in these code bases:
I get a linter warning about missing newline.

2022-04-05 20:14 UTC, hoangphamEclipse commented on README.md
>  This trace viewer depends on code from several other repos. Sometimes resolving issues in the trace viewer repo requires making changes in these code bases:
On my end on line 280, there was a trailing white space.

2022-04-05 20:15 UTC, bhufmann requested changes
Please remove the CONTRIBUTION.md file since it was renamed.

2022-04-05 20:35 UTC, bhufmann approved these changes
Looks good to me. Thanks for the update.

2022-04-06 20:34 UTC, Rodrigoplp-work approved these changes

2022-04-07 12:54 UTC, merged