Show/Hide events table columns
eclipse-cdt-cloud/theia-trace-extension pull request #734
Opened 2022-04-14 20:48 UTC by hriday-panchasara

- Added an optional 'Options menu button' in AbstractOutputComponent's Title Bar:
<img width="137" alt="Screen Shot 2022-04-14 at 3 47 48 PM" src="https://user-images.githubusercontent.com/92893187/163472738-d5629849-005c-4b40-bd3f-078441fc518e.png">

- Events table implements this button to open a dropdown list that allows users to toggle visibility of multiple columns
<img width="543" alt="Screen Shot 2022-04-14 at 3 47 14 PM" src="https://user-images.githubusercontent.com/92893187/163472666-39595f2e-50a3-4ae5-b686-ef39c5e5487d.png">

2022-04-22 14:18 UTC, PatrickTasse requested changes

2022-04-22 14:18 UTC, PatrickTasse commented on packages/react-components/style/output-components-style.css
> +    position: absolute;
It seems to me that as a menu popup, the dialog should appear in a position relative to the mouse cursor or the menu icon.

Especially that where it is placed now, and with no user indication of how to close the dialog (click outside?), the user might mistakenly think that the [x] close button is to close the dialog, but it closes the table output.

2022-04-22 14:18 UTC, PatrickTasse commented on packages/react-components/src/components/abstract-output-component.tsx
> +        if (event.target instanceof Node && this.optionsMenuRef.current?.contains(event.target)) {
This change belongs in the first commit?

2022-04-22 14:18 UTC, PatrickTasse commented on packages/react-components/style/output-components-style.css
> +    width: 250px;
These changes belong in the first commit?

2022-04-22 14:18 UTC, PatrickTasse commented on packages/react-components/src/components/abstract-output-component.tsx
> +                    <FontAwesomeIcon icon={faBars} />
I think the options menu button should be snapped below the close button, not floating when output height is resized.

2022-04-22 14:18 UTC, PatrickTasse commented on packages/react-components/src/components/table-output-component.tsx
> +                </thead>
In my opinion, this table header is unnecessary and I would prefer the checkboxes much closer to the column names.

2022-04-22 21:26 UTC, hriday-panchasara commented
@PatrickTasse Changes Made:
- Rebased so all changes belong to one commit
- Removed table header
- Options menu snapped below the close button. Clicking on this would open a dropdown menu. Dropdown menu has 'Toggle Columns' option - when clicked the table will appear. The idea is to have this dropdown also include 'Export View' and 'Pin View' options. I'll add them to this dropdown once this item has merged and I'll have to resolve merge conflicts in those PR's
![Screen Shot 2022-04-22 at 4 25 25 PM](https://user-images.githubusercontent.com/92893187/164797387-ad60cec6-95aa-4ac5-b087-e913e953f68d.png)
- Dropdown appears relative to menu icon

2022-04-28 19:55 UTC, PatrickTasse approved these changes

2022-05-04 16:51 UTC, bhufmann approved these changes
Looks good to me. Thanks for this feature.

2022-05-04 16:53 UTC, merged