xy-output-component: Deserialize for isScatterPlot
eclipse-cdt-cloud/theia-trace-extension pull request #744
Opened 2022-05-05 22:01 UTC by marco-miller

1. xy-output-component: Reverse negative if statement
2. xy-output-component: Deserialize for isScatterPlot

Each commit message should have their necessary details.

2022-05-10 17:44 UTC, marco-miller commented
Accidentally closed this PR by mistake; still WIP.

2022-05-24 20:35 UTC, marco-miller commented
> Code looks good. Once the corresponding tsp-typescript-version is available, then you can update this one with the updated yarn.lock file.

Thanks. I removed the `tsp-typescript-client@next` lines in `yarn.lock` to force `yarn` into updating those with the latest. I couldn't get `yarn upgrade` or other related commands to update that package prior.

This happened to also [update another (unrelated) line for `json-bigint`](https://github.com/eclipse-cdt-cloud/theia-trace-extension/compare/6bd5176e752ea00adafa5ad4aebd74c5a611d004..57aa021dd1685ee5a498c64332ce7ddf45cb6b92#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR9633). However that looks like a trivial update which had to happen anyway it seems.

2022-05-25 17:00 UTC, bhufmann requested changes

2022-05-26 17:34 UTC, bhufmann approved these changes
Thanks. Looks good to me.

2022-05-26 17:44 UTC, merged