Fire TSP client requests in parallel in getData function
eclipse-cdt-cloud/theia-trace-extension pull request #779
Opened 2022-07-06 16:49 UTC by williamsyang-work

Requests for States, Annotations, and Arrows are now fired simultaneously.

Annotation response data processing moved in front of states processing, since annotation response time is usually shorter.

Signed-off-by: Will Yang <william.yang@ericsson.com>

2022-07-07 17:15 UTC, MatthewKhouzam submitted a review, later dismissed
LGTM, but I asked for it.

2022-07-20 15:55 UTC, bhufmann requested changes

2022-07-20 15:55 UTC, bhufmann commented on packages/react-components/src/components/data-providers/tsp-data-provider.ts
> +            const tspClientAnnotationsResponse = await annotationsPromise;
when executing this await, all 3 created promises (for annotations, states and arrows) are triggered and the back-end requests are done. With this all 3 are sent in parallel. However, we should make it more explicit and schedule all 3 executions using Promise.all() or Promise.allSettled().

2022-07-29 15:24 UTC, bhufmann commented
@williamsyang-work any news on this one?

2022-08-01 18:25 UTC, bhufmann requested changes

2022-08-01 18:25 UTC, bhufmann commented on packages/react-components/src/components/data-providers/tsp-data-provider.ts
> +        const [tspClientAnnotationsResponse, tspClientStatesResponse, tspClientArrowsResponse] = [await annotationsPromise, await statesPromise, await arrowsPromise];
Use the following Promise.all() to make sure that the 3 promises are triggered at the same time:
`const [tspClientAnnotationsResponse, tspClientStatesResponse, tspClientArrowsResponse] = await Promise.all([annotationsPromise, statesPromise, arrowsPromise]);`

2022-08-01 18:45 UTC, bhufmann approved these changes
Looks good to me. Thanks for this improvement.

2022-08-01 18:47 UTC, MatthewKhouzam approved these changes
Looks good to me!

2022-08-01 18:47 UTC, merged