XY Chart refresh data model on resize
eclipse-cdt-cloud/theia-trace-extension pull request #794
Opened 2022-07-21 16:07 UTC by hriday-panchasara

xy chart updates data model when size of parent component (trace-context-component) is changed

[Screen Recording 2022-07-21 at 11.05.33 AM.webm](https://user-images.githubusercontent.com/92893187/180261591-0270e757-adf0-47e1-ba8e-3edf91792912.webm)

fixes #726

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

2022-07-27 19:44 UTC, hoangphamEclipse approved these changes
Thank you for the bug fix. I tested the change and it worked. The code also looks good.

2022-08-04 19:29 UTC, hoangphamEclipse commented
@hriday-panchasara  Looks good to me :)

2022-08-04 19:29 UTC, hoangphamEclipse approved these changes
Looks good to me! :)

2022-08-09 19:25 UTC, bhufmann requested changes
The fetching of the data should use a debouncer to avoid too many back-end requests.

2022-08-09 19:57 UTC, hriday-panchasara commented
> The fetching of the data should use a debouncer to avoid too many back-end requests.
Yup, throttling is already implemented thanks to PR #713

2022-08-24 15:35 UTC, Rodrigoplp-work approved these changes
Well done. And it seems PR #713 does in fact handle the throttling problem.

2022-08-30 19:48 UTC, bhufmann commented
> Well done. And it seems PR #713 does in fact handle the throttling problem.

I should have expanded the lines below in the diff view then I would have seen the throttling :-)

2022-08-30 19:49 UTC, bhufmann approved these changes
Thanks!

2022-08-30 19:49 UTC, merged