Add Events Table Shortcuts to the Keyboard Shortcuts Menu
eclipse-cdt-cloud/theia-trace-extension pull request #804
Opened 2022-08-10 17:16 UTC by hriday-panchasara

Helps fix #742

- The requested shortcuts described in #742 are implemented by default in all ag-grid tables: https://www.ag-grid.com/react-data-grid/keyboard-navigation/
- I added these shortcuts to the Keyboard Shortcuts menu to make them discoverable. I also added the following keyboard/mouse interactions:
        - Select Multiple rows: 'Shift + click' or 'Shift + arrow up/down'
        - Deselect rows: 'ctrl or meta key'
- In table-output-component I also noticed that 'space' is registered as a key interaction to replace multi-select with a single row, but was not sure how to describe it in the shortcuts menu as a user can single-click or use ctrl to remove multi-select
- Here's how the shortcuts menu looks now:
![Screen Shot 2022-08-10 at 12 15 02 PM](https://user-images.githubusercontent.com/92893187/183975398-0c0a6b5b-4e4d-451d-8d65-ab5309f1a715.png)

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

2022-08-12 13:52 UTC, hoangphamEclipse commented
Thank you for the PR. I tried the code out and it works. However, the navigation itself for the table is not very smooth.

[1]  A cell needs to be explicitly selected before the navigation with arrows key can work. When an event table is opened the first time, an event is selected, but the navigation does not work because no cells is selected. I don't know if this is the selected behavior. 

[2] When you deselect with Ctrl, you need to move to a new row before you can start selecting multiple row with Shift+Ctrl again.

> In table-output-component I also noticed that 'space' is registered as a key interaction to replace multi-select with a single row, but was not sure how to describe it in the shortcuts menu as a user can single-click or use ctrl to remove multi-select

Looks like the `Spacebar` is used to select a single row. So in addition to what you have mentioned, I can also select/highlight an entire row as well.

2022-08-12 19:46 UTC, hriday-panchasara commented
> Thank you for the PR. I tried the code out and it works. However, the navigation itself for the table is not very smooth.
> 
> [1] A cell needs to be explicitly selected before the navigation with arrows key can work. When an event table is opened the first time, an event is selected, but the navigation does not work because no cells is selected. I don't know if this is the expected behavior.
> 
> [2] When you deselect with `Ctrl`, you need to move to a new row before you can start selecting multiple row with `Shift+Ctrl` again.
> 
> > In table-output-component I also noticed that 'space' is registered as a key interaction to replace multi-select with a single row, but was not sure how to describe it in the shortcuts menu as a user can single-click or use ctrl to remove multi-select
> 
> Looks like the `Spacebar` is used to select a single row. So in addition to what you have mentioned, I can also select/highlight an entire row as well.

I believe [1] is expected behavior, in order to interact with a chart there needs to be tab focus which is indicated by a blue outline. This can be either achieved by clicking 'Tab' until you tab into the desired cell, or by clicking on it. For example on the xy-charts you need to click on the chart first or tab into it before attempting keyboard operations (zoom and pan through buttons).

For [2], you can click spacebar to select the current row rather than moving to another row for multi-select. In table-output-component, I noticed that only 'Shift + arrow up/down', 'Spacebar', and 'arrow up/down' result in row(s) being selected - any other key press would lead to gridapi.deselectAll(). This makes me believe that [2] is intentional behavior as well

2022-08-12 19:58 UTC, hriday-panchasara commented
Added the 'Spacebar' keybinding to the shortcuts menu:
![Screen Shot 2022-08-12 at 2 58 07 PM](https://user-images.githubusercontent.com/92893187/184433648-a7b8e711-d4a2-4010-9019-213d5c2de20b.png)

2022-08-22 00:43 UTC, hoangphamEclipse commented
> > Thank you for the PR. I tried the code out and it works. However, the navigation itself for the table is not very smooth.
> > [1] A cell needs to be explicitly selected before the navigation with arrows key can work. When an event table is opened the first time, an event is selected, but the navigation does not work because no cells is selected. I don't know if this is the expected behavior.
> > [2] When you deselect with `Ctrl`, you need to move to a new row before you can start selecting multiple row with `Shift+Ctrl` again.
> > > In table-output-component I also noticed that 'space' is registered as a key interaction to replace multi-select with a single row, but was not sure how to describe it in the shortcuts menu as a user can single-click or use ctrl to remove multi-select
> > 
> > 
> > Looks like the `Spacebar` is used to select a single row. So in addition to what you have mentioned, I can also select/highlight an entire row as well.
> 
> I believe [1] is expected behavior, in order to interact with a chart there needs to be tab focus which is indicated by a blue outline. This can be either achieved by clicking 'Tab' until you tab into the desired cell, or by clicking on it. For example on the xy-charts you need to click on the chart first or tab into it before attempting keyboard operations (zoom and pan through buttons).
> 
> For [2], you can click spacebar to select the current row rather than moving to another row for multi-select. In table-output-component, I noticed that only 'Shift + arrow up/down', 'Spacebar', and 'arrow up/down' result in row(s) being selected - any other key press would lead to gridapi.deselectAll(). This makes me believe that [2] is intentional behavior as well

Thank you @hriday-panchasara, this make sense. Also thank you for adding the `Spacebar` to the shortcut menu.

2022-08-22 00:45 UTC, hoangphamEclipse submitted a review, later dismissed

2022-08-22 20:05 UTC, Rodrigoplp-work submitted a review, later dismissed

2022-08-26 17:44 UTC, PatrickTasse requested changes

2022-08-26 17:44 UTC, PatrickTasse commented on theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/events-table-shortcuts-table.tsx
> +            <span className='shortcuts-table-header'>EVENTS TABLE NAVIGATION</span>
Should this be more generically "TABLE NAVIGATION" ?

It applies to output type "TABLE" which covers the Events Table but also now some instances of Latency Table.

2022-09-06 19:57 UTC, marco-miller approved these changes
LGTM too; thanks!

2022-09-06 19:58 UTC, merged