Toggle Open Trace File Picker with custom path
eclipse-cdt-cloud/theia-trace-extension pull request #814
Opened 2022-08-29 18:44 UTC by hriday-panchasara

Add the ability to open the trace file picker dialog with a custom root path if needed

Fixes #811

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

2022-08-29 21:55 UTC, marco-miller requested changes
- I'm unable to find the added command; is the PR missing anything, or am I (from the UI)?
- Minor: commit message lines have to be wrapped to max 72 chars per line.

2022-09-06 18:07 UTC, bhufmann requested changes

2022-09-06 18:27 UTC, bhufmann approved these changes

2022-09-06 18:28 UTC, bhufmann approved these changes
I tested it by changing the regular open procedure in TraceViewerToolbarContribution to use the new command and passed a custom path.

2022-09-06 20:14 UTC, marco-miller approved these changes
- Relying on the aforementioned test campaign; thanks.
- Had a comment about the commit message, but up to you to merge as is or apply it prior (@bhufmann and @hriday-panchasara).

2022-09-07 00:02 UTC, merged