Support window dragging with mouse-middle drag in xy charts
eclipse-cdt-cloud/theia-trace-extension pull request #833
Opened 2022-09-12 18:17 UTC by hriday-panchasara

Fixes #732

Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>

2022-09-12 19:23 UTC, marco-miller requested changes
Works well for me locally. Note, this PR fixes both `XY` and `TimeGraph` cases it seems. Without this patch, both cases are lacking mouse-middle button drag support, it seems. At least from my local point of view. And, I do see the hand pointer upon clicking that way.

2022-09-12 19:23 UTC, marco-miller commented on packages/react-components/src/components/xy-output-component.tsx
> +        console.log('onWheel called');
Should this be kept?

2022-09-12 20:08 UTC, hriday-panchasara commented on packages/react-components/src/components/xy-output-component.tsx
> +        console.log('onWheel called');
Oops, forgot to take it out

2022-09-12 20:17 UTC, marco-miller approved these changes
LGTM, with that note I posted above / earlier. Thanks!

2022-09-16 20:20 UTC, bhufmann approved these changes
LGTM. Thanks!

2022-09-16 20:20 UTC, merged