Toggle the filter tree for the trace overview
eclipse-cdt-cloud/theia-trace-extension pull request #858
Opened 2022-10-19 18:02 UTC by hoangphamEclipse

This commit creates a hamburger menu for the trace overview that will allow users to toggle the filter tree and select a different output view. The hamburger menu replaces the existing cog icon that is used for output source selection. A new state property is added to the AbstractTreeOutputComponent that allows showing and hiding the filter tree. The overview then toggles this state property.

2022-10-20 14:52 UTC, marco-miller requested changes
LGTM, with just a few nits.

2022-10-20 14:52 UTC, marco-miller commented on packages/react-components/src/components/abstract-tree-output-component.tsx
> +
Extra blank line introduced, would remove it.

2022-10-20 14:52 UTC, marco-miller commented on packages/react-components/src/components/abstract-tree-output-component.tsx
> +
Extra blank line?

2022-10-20 15:22 UTC, marco-miller submitted a review, later dismissed
Letting you @hoangphamEclipse decide if you need a second review; thanks, let me/us know.

2022-10-20 19:27 UTC, Rodrigoplp-work requested changes
Awesome!
Could you add the name of the selected source to the title of the overview (the text that shows on the vertical bar on the left of the chart)?
So, after the user clicks on the hamburger button, clicks on "Select source output" and chooses for example "CPU Usage", the title would change from "Overview" to "Overview - CPU Usage".
If that is too much work we can leave it to be done on another ticket, as this was not specified in the requirements.

2022-10-21 14:59 UTC, hoangphamEclipse commented
> Awesome! Could you add the name of the selected source to the title of the overview (the text that shows on the vertical bar on the left of the chart)? So, after the user clicks on the hamburger button, clicks on "Select source output" and chooses for example "CPU Usage", the title would change from "Overview" to "Overview - CPU Usage". If that is too much work we can leave it to be done on another ticket, as this was not specified in the requirements.

This can be done in another PR.

2022-10-21 15:57 UTC, Rodrigoplp-work approved these changes

2022-10-21 16:19 UTC, marco-miller approved these changes
LGTM still, letting you @Rodrigoplp-work rebase/merge at will, if you tested this latest update. I didn't, but I tested an earlier version (of this PR).

2022-10-24 20:00 UTC, merged