Fixes large tables on high-dpi monitors
eclipse-cdt-cloud/theia-trace-extension pull request #867
Opened 2022-11-07 00:40 UTC by Rodrigoplp-work

The solution is to reduce the amount of rows a page can have. Previous value of 500,000 was too large for monitors with high DPI.

Fixes #862.

Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca

2022-11-07 19:17 UTC, marco-miller approved these changes
LGTM but I use my base laptop screen, so my testing is limited for that specific Issue.

2022-11-08 16:32 UTC, MatthewKhouzam commented
I have a high dpi monitor, I confirm it works, I would like to have an explanation of why though.

2022-11-08 16:33 UTC, MatthewKhouzam approved these changes
We need to know why though.

2022-11-10 00:42 UTC, bhufmann commented
Can we merge this one?

2022-11-10 19:40 UTC, marco-miller commented
> Can we merge this one?

I think @MatthewKhouzam was expecting a documented (yet potentially brief) explanation first. Ideally persisted in the git commit message, or so I propose.

2022-11-24 21:03 UTC, Rodrigoplp-work commented
Found the reason behind the problem. Updated the commit message and the PR post.

2022-11-25 13:30 UTC, marco-miller commented
Good findings. There is a typo in the commit message and PR header; 'streching' should read 'stretching'.

2022-11-25 13:30 UTC, marco-miller requested changes
Per previously posted comment; minor.

2022-11-25 14:08 UTC, marco-miller approved these changes
Thanks!

2022-11-25 16:36 UTC, MatthewKhouzam approved these changes

2022-11-25 16:36 UTC, merged