Created a widget for properties view in react-components
eclipse-cdt-cloud/theia-trace-extension pull request #892
Opened 2022-12-09 21:26 UTC by ngondalia

Changes made:

- Implemented a properties widget in react-components
- Change theia implementation to use the widget from react-components

This will move the properties widget to the react-components npm package, so it can be used by both the theia extension and vscode extension.

Signed-off-by: Neel Gondalia ngondalia@blackberry.com

2022-12-20 19:32 UTC, bhufmann requested changes
Thanks for the contribution. It works well. 

I'd like to ask you though to update some names. I think it makes sense to do it now because before it becomes API that is used with Theia and VsCode. 

Basically, I'd like that tooltip is replaced with item properties where it makes sense. I tried to find the relevant places that need to be updated to make it easier. Refactoring of you code editor should make it easier. Add the renaming as a second commit to the PR. 

- in SignalManager.tsx: rename signal name and fireTooltipSignal(tooltip) to 
```
ITEM_PROPERTIES_UPDATED: 'item properties updated',
```
```
fireItemPropertiesSignalUpdated(properties?: { [key: string]: string; }): void {
        this.emit(Signals.ITEM_PROPERTIES_UPDATED, properties);
    }
- under `packages/...' directory: `trace-explorer-tooltip-widget.tsx` -> `trace-explorer-properties-widget.tsx`
- under `theia-extension/viewer-prototype/...` directory: `trace-explorer-tooltip-widget.tsx` -> `theia-trace-explorer-properties-widget.tsx`
```
- under `packages/react-compenents/src/trace-explorer`: rename `trace-explorer-tooltip-widget.tsx` to `trace-explorer-properties-widget.tsx`
- under `theia-extension/...`: rename `trace-explorer-tooltip-widget.tsx` to `theia-trace-explorer-properties-widget.tsx`

2022-12-20 19:32 UTC, bhufmann commented on theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-tooltip-widget.tsx
>  export class TraceExplorerTooltipWidget extends ReactWidget {
This class should be renamed to `TraceExplorerItemPropertiesWidget`

2023-01-03 19:18 UTC, bhufmann approved these changes
Looks good to me! Thank you for the contribution.

2023-01-03 22:15 UTC, Rodrigoplp-work approved these changes
Thank you for the contribution.

2023-01-03 22:27 UTC, merged