Use new TSP APIs for XY entries to check for default entries
eclipse-cdt-cloud/theia-trace-extension pull request #905
Opened 2023-01-10 21:33 UTC by bhufmann

If 'isDefault' flag is set for an XY entry, then check it in the tree and fetch its XY data to fill the XY graph once the analysis is complete.

- Fixes #786 
- Requires to build: https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/70
- Corresponding: TSP specitication: https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/85
- Contributes to https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/786

Example back-end implementation:
- https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/199323/1
- https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/199324

Signed-off-by: Bernd Hufmann <bernd.hufmann@ericsson.com>

2023-01-13 15:09 UTC, marco-miller requested changes
LGTM, and works well for me locally, along with patch's client and server counterparts. Should build here too once client's can be merged thus updating its version in this repo.

2023-01-13 20:40 UTC, marco-miller approved these changes
Unblocking a potential merge while considering the upcoming client bump within.

2023-01-13 21:13 UTC, bhufmann commented
> Unblocking a potential merge while considering the upcoming client bump within.

@marco-miller thanks. I upgraded to the latest tsp-typescript-client to support the new flag.

2023-01-16 13:25 UTC, marco-miller approved these changes
LGTM.

2023-01-16 13:47 UTC, merged