Add performance analysis for timeline chart
eclipse-cdt-cloud/theia-trace-extension pull request #923
Opened 2023-02-02 16:24 UTC by hoangphamEclipse

Currently, the timeline chart faces many performace issues, especially with zooming, panning and resizing. This document attempts to identify the bottleneck of the chart and records tests with replicable parameters so that performance can be measured and improved.

Signed-off-by: Hoang Thuan Pham <hoang.pham@calian.ca>

2023-02-13 20:07 UTC, MatthewKhouzam commented
Please add time units to tables. But great work!

2023-02-13 20:15 UTC, bhufmann requested changes

2023-02-13 20:15 UTC, bhufmann commented on doc/performance/0001-timeline-chart-performance-analysis.md
> +Number of rows removed upon update ~= 4578
should be states instead of rows

2023-02-13 20:15 UTC, bhufmann commented on doc/performance/0001-timeline-chart-performance-analysis.md
> +Number of rows removed upon update ~= 112311
states

2023-02-13 20:15 UTC, bhufmann commented on doc/performance/0001-timeline-chart-performance-analysis.md
> +Number of rows removed upon update ~= 4578
states

2023-02-13 20:15 UTC, bhufmann commented on doc/performance/0001-timeline-chart-performance-analysis.md
> +Number of rows removed upon update ~= 112311
states

2023-02-14 15:21 UTC, hoangphamEclipse commented on doc/performance/0001-timeline-chart-performance-analysis.md
> +Number of rows removed upon update ~= 4578
Thanks Bernd, I will fix that.

2023-02-17 18:20 UTC, bhufmann approved these changes
I'm ok to merged it as is. Thanks a lot.

2023-02-21 22:20 UTC, MatthewKhouzam approved these changes
great job.

2023-02-22 16:25 UTC, merged