Move keyboard shortcuts table to traceviewer-react-components
eclipse-cdt-cloud/theia-trace-extension pull request #978
Opened 2023-05-23 00:26 UTC by hriday-panchasara

This would allow it to be used by both theia and vscode extension

2023-05-24 15:19 UTC, bhufmann submitted a review, later dismissed
Looks good to me. Thanks!

2023-05-26 18:56 UTC, hoangphamEclipse commented
Hi @hriday-panchasara, there have been some changes made regarding the CSS classes in the trace extension. Any CSS variables that take up different values in different environment (e.g Theia vs VsCode) must be made mappable. That is, the variable prefix must be `--trace-viewer`. You can see what exactly that you need to do in the following PR #977.

2023-05-26 19:00 UTC, hoangphamEclipse requested changes

2023-05-26 19:00 UTC, hoangphamEclipse commented on packages/react-components/style/trace-explorer.css
> +    color: var(--theia-button-background);
Please rebase the code. CSS variables that start with `--theia` should be replaced by `--trace-viewer`.

2023-05-26 19:00 UTC, hoangphamEclipse commented on packages/react-components/style/trace-explorer.css
> +    background-color: var(--theia-keybindingLabel-background);
CSS variables that start with --theia should be replaced by --trace-viewer. Then, these variables can be mapped to Theia variables in trace-viewer.css. See PR #977.

2023-05-29 14:47 UTC, hoangphamEclipse commented
Thank you. LGTM.

2023-05-29 14:47 UTC, hoangphamEclipse approved these changes

2023-05-29 19:06 UTC, bhufmann approved these changes

2023-05-30 15:03 UTC, merged